Feedbacks
KetiRudneva/lubimovka pull request #11
Opened 2022-06-09 13:34 UTC by KetiRudneva

Добавлена секция отзывы

2022-06-09 17:38 UTC, tsharon-byte commented on blocks/card/__author/card__author.css
> +  font-family: 'NeueMachina', 'Arial', sans-serif;
font-family: 'Neue Machina';
Пробел забыла)

2022-06-09 17:38 UTC, tsharon-byte commented on blocks/card/card.css
> +  background-color: #fff;
можно заменить на 
var(--secondary-bg-color);

2022-06-09 17:38 UTC, tsharon-byte commented on blocks/feedbacks/__container/feedbacks__container.css
> +  background-color: #fff;
можно заменить на
var(--secondary-bg-color);

2022-06-09 17:38 UTC, tsharon-byte commented on blocks/feedbacks/__title/feedbacks__title.css
> +  font-family: 'NeueMachina', 'Arial', sans-serif;
Название шрифта с пробелом

2022-06-09 17:38 UTC, tsharon-byte commented on blocks/reviews/__title/reviews__title.css
> +  font-family: 'NeueMachina', 'Arial', sans-serif;
название шрифта с пробелом

2022-06-10 07:40 UTC, tsharon-byte requested changes

2022-06-10 07:40 UTC, tsharon-byte commented on index.html
> +                      <svg width="51" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
В папке с анимациями лежат гифки на эти кнопки. Их наверное надо использовать

2022-06-10 07:40 UTC, tsharon-byte commented on index.html
> +                    <button class="reviews__next-button" type="button" aria-label="Следующий слайд">
В папке с анимациями лежат гифки на эти кнопки. Их наверное надо использовать

2022-06-10 07:40 UTC, tsharon-byte commented on index.html
> +                    <button class="feedbacks__prev-button" type="button" aria-label="Предыдущий слайд">
В папке с анимациями лежат гифки на эти кнопки. Их наверное надо использовать

2022-06-10 07:40 UTC, tsharon-byte commented on index.html
> +                      <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
В папке с анимациями лежат гифки на эти кнопки. Их наверное надо использовать

2022-06-10 07:40 UTC, tsharon-byte commented on index.html
> +                      <img class="card__circles" src="./images/circles.png" alt="кружки"/>
Нужно каждую точку сделать отдельным элементом.
Потом с помощью JS нужно будет менять цвет кнопки при пролистывании рецензий/отзывов

2022-06-14 09:01 UTC, KetiRudneva commented on index.html
> +                      <img class="card__circles" src="./images/circles.png" alt="кружки"/>
Это я сделаю в следующей итерации

2022-06-14 09:13 UTC, KetiRudneva commented on index.html
> +                      <svg width="51" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
Попробую реализовать анимацию самостоятельно. Если не получится, поменяю кнопку в следующей итерации.

2022-06-14 09:14 UTC, KetiRudneva commented on index.html
> +                    <button class="reviews__next-button" type="button" aria-label="Следующий слайд">
Попробую реализовать анимацию самостоятельно. Если не получится, поменяю кнопку в следующей итерации.

2022-06-14 09:14 UTC, KetiRudneva commented on index.html
> +                    <button class="feedbacks__prev-button" type="button" aria-label="Предыдущий слайд">
Попробую реализовать анимацию самостоятельно. Если не получится, поменяю кнопку в следующей итерации.

2022-06-14 09:14 UTC, KetiRudneva commented on index.html
> +                      <svg width="50" height="50" viewBox="0 0 50 50" fill="none" xmlns="http://www.w3.org/2000/svg">
Попробую реализовать анимацию самостоятельно. Если не получится, поменяю кнопку в следующей итерации.

2022-06-14 09:14 UTC, merged